### ISSUE TITLE
Any real world examples?

### ISSUE THREAD

**Issue by danielo515** [RobertBorghese/reflaxe#1]
Hello, and thank you for this library. It looks amazing.
I was wondering if there are any real world examples? Will love to take a look at something built with it.

**Comment by RobertBorghese** [comment]
Thank you for your kind words! This project is incomplete at the moment (only been working on it for two weeks) but it exists to help support me with my development with my [GDScript Haxe target](https://github.com/RobertBorghese/Haxe-CompileToGDScript). So if you want to keep up with an implementation of a macro-built Haxe target, I'd recommend checking that out. :D

**Comment by danielo515** [comment]
That's perfect! And thank you for other project too!

**Comment by vega0** [comment]
https://github.com/RobertBorghese/reflaxe.CSharp
